import { hasFirebaseCredentials } from '../config/env.js';
import { getFirestore, admin } from '../config/firebase.js';
import { logger } from '../utils/logger.js';
import { trainerService } from '../services/trainerService.js';

/**
 * Generic dev helper that promotes a Firebase Auth uid to a TRAINER account
 * using the Firebase Admin SDK (bypasses client rules). It is NOT a privileged
 * single-trainer bootstrap: there is no hardcoded name or referral code, and no
 * trainer is special-cased. The referral code is GENERATED by the same
 * production generator every trainer uses, guaranteeing uniqueness.
 *
 * Idempotent: re-running does not create a duplicate trainer or a second code.
 *
 * Usage:
 *   SEED_TRAINER_UID=<firebase-auth-uid> [SEED_TRAINER_NAME="Coach Name"] npm run seed:trainer
 *
 * Requires Firebase Admin credentials (see docs/SETUP.md). The uid MUST be a
 * real Firebase Auth uid (create the trainer login account first). Trainers can
 * also self-register through the app (POST /api/auth/register-trainer); this
 * helper exists only for local/dev convenience and may be removed if the team
 * prefers self-registration as the sole path.
 */
async function main(): Promise<void> {
  if (!hasFirebaseCredentials()) {
    logger.error(
      'Cannot seed trainer: Firebase Admin credentials are not configured. ' +
        'Set FIREBASE_* env vars or GOOGLE_APPLICATION_CREDENTIALS. See docs/SETUP.md.',
    );
    process.exitCode = 1;
    return;
  }

  const uid = process.env.SEED_TRAINER_UID?.trim();
  if (!uid) {
    logger.error(
      'Cannot seed trainer: SEED_TRAINER_UID is required (the Firebase Auth uid of the trainer account). ' +
        'Create the trainer login via Firebase Authentication first, then run: ' +
        'SEED_TRAINER_UID=<uid> npm run seed:trainer',
    );
    process.exitCode = 1;
    return;
  }

  const name = process.env.SEED_TRAINER_NAME?.trim() || 'Trainer';

  // Touch Firestore to surface credential/connectivity problems early and keep
  // the Admin SDK import meaningful for the dev workflow.
  void admin;
  void getFirestore();

  const result = await trainerService.ensureTrainerAccount(uid, { name });

  logger.info(
    { uid: result.trainerId, referralCode: result.referralCode },
    'Trainer seed complete (generated referral code).',
  );
}

main().catch((err) => {
  logger.error({ err }, 'Trainer seed failed');
  process.exitCode = 1;
});
